/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletsRouteImport } from './routes/wallets'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as TransactionDetailRouteImport } from './routes/transaction-detail'
import { Route as TestSupabaseRouteImport } from './routes/test-supabase'
import { Route as TestLoginButtonRouteImport } from './routes/test-login-button'
import { Route as TestDatepickerRouteImport } from './routes/test-datepicker'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as EditcategoryRouteImport } from './routes/editcategory'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as AppRouteImport } from './routes/app'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as Sin1SplatRouteImport } from './routes/sin1.$'
import { Route as R5smsSplatRouteImport } from './routes/r5sms.$'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AppWalletsRouteImport } from './routes/app/wallets'
import { Route as AppTransactionsRouteImport } from './routes/app/transactions'
import { Route as AppTransactionDetailRouteImport } from './routes/app/transaction-detail'
import { Route as AppTestSupabaseRouteImport } from './routes/app/test-supabase'
import { Route as AppTestLoginButtonRouteImport } from './routes/app/test-login-button'
import { Route as AppTestDatepickerRouteImport } from './routes/app/test-datepicker'
import { Route as AppStatisticsRouteImport } from './routes/app/statistics'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppEditcategoryRouteImport } from './routes/app/editcategory'
import { Route as AppBudgetRouteImport } from './routes/app/budget'
import { Route as ApiAiGeminiFinanceInsightRouteImport } from './routes/api/ai/gemini-finance-insight'

const WalletsRoute = WalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionDetailRoute = TransactionDetailRouteImport.update({
  id: '/transaction-detail',
  path: '/transaction-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const TestSupabaseRoute = TestSupabaseRouteImport.update({
  id: '/test-supabase',
  path: '/test-supabase',
  getParentRoute: () => rootRouteImport,
} as any)
const TestLoginButtonRoute = TestLoginButtonRouteImport.update({
  id: '/test-login-button',
  path: '/test-login-button',
  getParentRoute: () => rootRouteImport,
} as any)
const TestDatepickerRoute = TestDatepickerRouteImport.update({
  id: '/test-datepicker',
  path: '/test-datepicker',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const EditcategoryRoute = EditcategoryRouteImport.update({
  id: '/editcategory',
  path: '/editcategory',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const Sin1SplatRoute = Sin1SplatRouteImport.update({
  id: '/sin1/$',
  path: '/sin1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R5smsSplatRoute = R5smsSplatRouteImport.update({
  id: '/r5sms/$',
  path: '/r5sms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletsRoute = AppWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionDetailRoute = AppTransactionDetailRouteImport.update({
  id: '/transaction-detail',
  path: '/transaction-detail',
  getParentRoute: () => AppRoute,
} as any)
const AppTestSupabaseRoute = AppTestSupabaseRouteImport.update({
  id: '/test-supabase',
  path: '/test-supabase',
  getParentRoute: () => AppRoute,
} as any)
const AppTestLoginButtonRoute = AppTestLoginButtonRouteImport.update({
  id: '/test-login-button',
  path: '/test-login-button',
  getParentRoute: () => AppRoute,
} as any)
const AppTestDatepickerRoute = AppTestDatepickerRouteImport.update({
  id: '/test-datepicker',
  path: '/test-datepicker',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppEditcategoryRoute = AppEditcategoryRouteImport.update({
  id: '/editcategory',
  path: '/editcategory',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AppRoute,
} as any)
const ApiAiGeminiFinanceInsightRoute =
  ApiAiGeminiFinanceInsightRouteImport.update({
    id: '/api/ai/gemini-finance-insight',
    path: '/api/ai/gemini-finance-insight',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/budget': typeof BudgetRoute
  '/editcategory': typeof EditcategoryRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/test-datepicker': typeof TestDatepickerRoute
  '/test-login-button': typeof TestLoginButtonRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/transaction-detail': typeof TransactionDetailRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/editcategory': typeof AppEditcategoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/test-datepicker': typeof AppTestDatepickerRoute
  '/app/test-login-button': typeof AppTestLoginButtonRoute
  '/app/test-supabase': typeof AppTestSupabaseRoute
  '/app/transaction-detail': typeof AppTransactionDetailRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/gemini-finance-insight': typeof ApiAiGeminiFinanceInsightRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/budget': typeof BudgetRoute
  '/editcategory': typeof EditcategoryRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/test-datepicker': typeof TestDatepickerRoute
  '/test-login-button': typeof TestLoginButtonRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/transaction-detail': typeof TransactionDetailRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/editcategory': typeof AppEditcategoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/test-datepicker': typeof AppTestDatepickerRoute
  '/app/test-login-button': typeof AppTestLoginButtonRoute
  '/app/test-supabase': typeof AppTestSupabaseRoute
  '/app/transaction-detail': typeof AppTransactionDetailRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
  '/app': typeof AppIndexRoute
  '/api/ai/gemini-finance-insight': typeof ApiAiGeminiFinanceInsightRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/app': typeof AppRouteWithChildren
  '/budget': typeof BudgetRoute
  '/editcategory': typeof EditcategoryRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/statistics': typeof StatisticsRoute
  '/terms': typeof TermsRoute
  '/test-datepicker': typeof TestDatepickerRoute
  '/test-login-button': typeof TestLoginButtonRoute
  '/test-supabase': typeof TestSupabaseRoute
  '/transaction-detail': typeof TransactionDetailRoute
  '/transactions': typeof TransactionsRoute
  '/wallets': typeof WalletsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/editcategory': typeof AppEditcategoryRoute
  '/app/profile': typeof AppProfileRoute
  '/app/statistics': typeof AppStatisticsRoute
  '/app/test-datepicker': typeof AppTestDatepickerRoute
  '/app/test-login-button': typeof AppTestLoginButtonRoute
  '/app/test-supabase': typeof AppTestSupabaseRoute
  '/app/transaction-detail': typeof AppTransactionDetailRoute
  '/app/transactions': typeof AppTransactionsRoute
  '/app/wallets': typeof AppWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
  '/app/': typeof AppIndexRoute
  '/api/ai/gemini-finance-insight': typeof ApiAiGeminiFinanceInsightRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/app'
    | '/budget'
    | '/editcategory'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/statistics'
    | '/terms'
    | '/test-datepicker'
    | '/test-login-button'
    | '/test-supabase'
    | '/transaction-detail'
    | '/transactions'
    | '/wallets'
    | '/app/budget'
    | '/app/editcategory'
    | '/app/profile'
    | '/app/statistics'
    | '/app/test-datepicker'
    | '/app/test-login-button'
    | '/app/test-supabase'
    | '/app/transaction-detail'
    | '/app/transactions'
    | '/app/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
    | '/app/'
    | '/api/ai/gemini-finance-insight'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/budget'
    | '/editcategory'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/statistics'
    | '/terms'
    | '/test-datepicker'
    | '/test-login-button'
    | '/test-supabase'
    | '/transaction-detail'
    | '/transactions'
    | '/wallets'
    | '/app/budget'
    | '/app/editcategory'
    | '/app/profile'
    | '/app/statistics'
    | '/app/test-datepicker'
    | '/app/test-login-button'
    | '/app/test-supabase'
    | '/app/transaction-detail'
    | '/app/transactions'
    | '/app/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
    | '/app'
    | '/api/ai/gemini-finance-insight'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/app'
    | '/budget'
    | '/editcategory'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/profile'
    | '/reset-password'
    | '/signup'
    | '/statistics'
    | '/terms'
    | '/test-datepicker'
    | '/test-login-button'
    | '/test-supabase'
    | '/transaction-detail'
    | '/transactions'
    | '/wallets'
    | '/app/budget'
    | '/app/editcategory'
    | '/app/profile'
    | '/app/statistics'
    | '/app/test-datepicker'
    | '/app/test-login-button'
    | '/app/test-supabase'
    | '/app/transaction-detail'
    | '/app/transactions'
    | '/app/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
    | '/app/'
    | '/api/ai/gemini-finance-insight'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AppRoute: typeof AppRouteWithChildren
  BudgetRoute: typeof BudgetRoute
  EditcategoryRoute: typeof EditcategoryRoute
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StatisticsRoute: typeof StatisticsRoute
  TermsRoute: typeof TermsRoute
  TestDatepickerRoute: typeof TestDatepickerRoute
  TestLoginButtonRoute: typeof TestLoginButtonRoute
  TestSupabaseRoute: typeof TestSupabaseRoute
  TransactionDetailRoute: typeof TransactionDetailRoute
  TransactionsRoute: typeof TransactionsRoute
  WalletsRoute: typeof WalletsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  R5smsSplatRoute: typeof R5smsSplatRoute
  Sin1SplatRoute: typeof Sin1SplatRoute
  ApiAiGeminiFinanceInsightRoute: typeof ApiAiGeminiFinanceInsightRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallets': {
      id: '/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof WalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transaction-detail': {
      id: '/transaction-detail'
      path: '/transaction-detail'
      fullPath: '/transaction-detail'
      preLoaderRoute: typeof TransactionDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-supabase': {
      id: '/test-supabase'
      path: '/test-supabase'
      fullPath: '/test-supabase'
      preLoaderRoute: typeof TestSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-login-button': {
      id: '/test-login-button'
      path: '/test-login-button'
      fullPath: '/test-login-button'
      preLoaderRoute: typeof TestLoginButtonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-datepicker': {
      id: '/test-datepicker'
      path: '/test-datepicker'
      fullPath: '/test-datepicker'
      preLoaderRoute: typeof TestDatepickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editcategory': {
      id: '/editcategory'
      path: '/editcategory'
      fullPath: '/editcategory'
      preLoaderRoute: typeof EditcategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/sin1/$': {
      id: '/sin1/$'
      path: '/sin1/$'
      fullPath: '/sin1/$'
      preLoaderRoute: typeof Sin1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r5sms/$': {
      id: '/r5sms/$'
      path: '/r5sms/$'
      fullPath: '/r5sms/$'
      preLoaderRoute: typeof R5smsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallets': {
      id: '/app/wallets'
      path: '/wallets'
      fullPath: '/app/wallets'
      preLoaderRoute: typeof AppWalletsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/transaction-detail': {
      id: '/app/transaction-detail'
      path: '/transaction-detail'
      fullPath: '/app/transaction-detail'
      preLoaderRoute: typeof AppTransactionDetailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/test-supabase': {
      id: '/app/test-supabase'
      path: '/test-supabase'
      fullPath: '/app/test-supabase'
      preLoaderRoute: typeof AppTestSupabaseRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/test-login-button': {
      id: '/app/test-login-button'
      path: '/test-login-button'
      fullPath: '/app/test-login-button'
      preLoaderRoute: typeof AppTestLoginButtonRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/test-datepicker': {
      id: '/app/test-datepicker'
      path: '/test-datepicker'
      fullPath: '/app/test-datepicker'
      preLoaderRoute: typeof AppTestDatepickerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statistics': {
      id: '/app/statistics'
      path: '/statistics'
      fullPath: '/app/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/editcategory': {
      id: '/app/editcategory'
      path: '/editcategory'
      fullPath: '/app/editcategory'
      preLoaderRoute: typeof AppEditcategoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/ai/gemini-finance-insight': {
      id: '/api/ai/gemini-finance-insight'
      path: '/api/ai/gemini-finance-insight'
      fullPath: '/api/ai/gemini-finance-insight'
      preLoaderRoute: typeof ApiAiGeminiFinanceInsightRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppBudgetRoute: typeof AppBudgetRoute
  AppEditcategoryRoute: typeof AppEditcategoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppTestDatepickerRoute: typeof AppTestDatepickerRoute
  AppTestLoginButtonRoute: typeof AppTestLoginButtonRoute
  AppTestSupabaseRoute: typeof AppTestSupabaseRoute
  AppTransactionDetailRoute: typeof AppTransactionDetailRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppWalletsRoute: typeof AppWalletsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBudgetRoute: AppBudgetRoute,
  AppEditcategoryRoute: AppEditcategoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppStatisticsRoute: AppStatisticsRoute,
  AppTestDatepickerRoute: AppTestDatepickerRoute,
  AppTestLoginButtonRoute: AppTestLoginButtonRoute,
  AppTestSupabaseRoute: AppTestSupabaseRoute,
  AppTransactionDetailRoute: AppTransactionDetailRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppWalletsRoute: AppWalletsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AppRoute: AppRouteWithChildren,
  BudgetRoute: BudgetRoute,
  EditcategoryRoute: EditcategoryRoute,
  ForgotpasswordRoute: ForgotpasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StatisticsRoute: StatisticsRoute,
  TermsRoute: TermsRoute,
  TestDatepickerRoute: TestDatepickerRoute,
  TestLoginButtonRoute: TestLoginButtonRoute,
  TestSupabaseRoute: TestSupabaseRoute,
  TransactionDetailRoute: TransactionDetailRoute,
  TransactionsRoute: TransactionsRoute,
  WalletsRoute: WalletsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  R5smsSplatRoute: R5smsSplatRoute,
  Sin1SplatRoute: Sin1SplatRoute,
  ApiAiGeminiFinanceInsightRoute: ApiAiGeminiFinanceInsightRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
