/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ForgotpasswordRouteImport } from './routes/forgotpassword'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as Sin1SplatRouteImport } from './routes/sin1.$'
import { Route as R5smsSplatRouteImport } from './routes/r5sms.$'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthenticatedWalletsRouteImport } from './routes/_authenticated/wallets'
import { Route as AuthenticatedTransactionsRouteImport } from './routes/_authenticated/transactions'
import { Route as AuthenticatedTransactionDetailRouteImport } from './routes/_authenticated/transaction-detail'
import { Route as AuthenticatedTestSupabaseRouteImport } from './routes/_authenticated/test-supabase'
import { Route as AuthenticatedTestLoginButtonRouteImport } from './routes/_authenticated/test-login-button'
import { Route as AuthenticatedTestDatepickerRouteImport } from './routes/_authenticated/test-datepicker'
import { Route as AuthenticatedStatisticsRouteImport } from './routes/_authenticated/statistics'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedEditcategoryRouteImport } from './routes/_authenticated/editcategory'
import { Route as AuthenticatedBudgetRouteImport } from './routes/_authenticated/budget'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotpasswordRoute = ForgotpasswordRouteImport.update({
  id: '/forgotpassword',
  path: '/forgotpassword',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Sin1SplatRoute = Sin1SplatRouteImport.update({
  id: '/sin1/$',
  path: '/sin1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R5smsSplatRoute = R5smsSplatRouteImport.update({
  id: '/r5sms/$',
  path: '/r5sms/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletsRoute = AuthenticatedWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTransactionsRoute =
  AuthenticatedTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTransactionDetailRoute =
  AuthenticatedTransactionDetailRouteImport.update({
    id: '/transaction-detail',
    path: '/transaction-detail',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestSupabaseRoute =
  AuthenticatedTestSupabaseRouteImport.update({
    id: '/test-supabase',
    path: '/test-supabase',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestLoginButtonRoute =
  AuthenticatedTestLoginButtonRouteImport.update({
    id: '/test-login-button',
    path: '/test-login-button',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestDatepickerRoute =
  AuthenticatedTestDatepickerRouteImport.update({
    id: '/test-datepicker',
    path: '/test-datepicker',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStatisticsRoute = AuthenticatedStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditcategoryRoute =
  AuthenticatedEditcategoryRouteImport.update({
    id: '/editcategory',
    path: '/editcategory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBudgetRoute = AuthenticatedBudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof AuthenticatedIndexRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/editcategory': typeof AuthenticatedEditcategoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/test-datepicker': typeof AuthenticatedTestDatepickerRoute
  '/test-login-button': typeof AuthenticatedTestLoginButtonRoute
  '/test-supabase': typeof AuthenticatedTestSupabaseRoute
  '/transaction-detail': typeof AuthenticatedTransactionDetailRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/budget': typeof AuthenticatedBudgetRoute
  '/editcategory': typeof AuthenticatedEditcategoryRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statistics': typeof AuthenticatedStatisticsRoute
  '/test-datepicker': typeof AuthenticatedTestDatepickerRoute
  '/test-login-button': typeof AuthenticatedTestLoginButtonRoute
  '/test-supabase': typeof AuthenticatedTestSupabaseRoute
  '/transaction-detail': typeof AuthenticatedTransactionDetailRoute
  '/transactions': typeof AuthenticatedTransactionsRoute
  '/wallets': typeof AuthenticatedWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgotpassword': typeof ForgotpasswordRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/offline': typeof OfflineRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/_authenticated/budget': typeof AuthenticatedBudgetRoute
  '/_authenticated/editcategory': typeof AuthenticatedEditcategoryRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/statistics': typeof AuthenticatedStatisticsRoute
  '/_authenticated/test-datepicker': typeof AuthenticatedTestDatepickerRoute
  '/_authenticated/test-login-button': typeof AuthenticatedTestLoginButtonRoute
  '/_authenticated/test-supabase': typeof AuthenticatedTestSupabaseRoute
  '/_authenticated/transaction-detail': typeof AuthenticatedTransactionDetailRoute
  '/_authenticated/transactions': typeof AuthenticatedTransactionsRoute
  '/_authenticated/wallets': typeof AuthenticatedWalletsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/r5sms/$': typeof R5smsSplatRoute
  '/sin1/$': typeof Sin1SplatRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/budget'
    | '/editcategory'
    | '/profile'
    | '/statistics'
    | '/test-datepicker'
    | '/test-login-button'
    | '/test-supabase'
    | '/transaction-detail'
    | '/transactions'
    | '/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/budget'
    | '/editcategory'
    | '/profile'
    | '/statistics'
    | '/test-datepicker'
    | '/test-login-button'
    | '/test-supabase'
    | '/transaction-detail'
    | '/transactions'
    | '/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
    | '/'
  id:
    | '__root__'
    | '/$'
    | '/_authenticated'
    | '/forgotpassword'
    | '/landing'
    | '/login'
    | '/offline'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/_authenticated/budget'
    | '/_authenticated/editcategory'
    | '/_authenticated/profile'
    | '/_authenticated/statistics'
    | '/_authenticated/test-datepicker'
    | '/_authenticated/test-login-button'
    | '/_authenticated/test-supabase'
    | '/_authenticated/transaction-detail'
    | '/_authenticated/transactions'
    | '/_authenticated/wallets'
    | '/auth/callback'
    | '/r5sms/$'
    | '/sin1/$'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotpasswordRoute: typeof ForgotpasswordRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  OfflineRoute: typeof OfflineRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  R5smsSplatRoute: typeof R5smsSplatRoute
  Sin1SplatRoute: typeof Sin1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotpassword': {
      id: '/forgotpassword'
      path: '/forgotpassword'
      fullPath: '/forgotpassword'
      preLoaderRoute: typeof ForgotpasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/sin1/$': {
      id: '/sin1/$'
      path: '/sin1/$'
      fullPath: '/sin1/$'
      preLoaderRoute: typeof Sin1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r5sms/$': {
      id: '/r5sms/$'
      path: '/r5sms/$'
      fullPath: '/r5sms/$'
      preLoaderRoute: typeof R5smsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallets': {
      id: '/_authenticated/wallets'
      path: '/wallets'
      fullPath: '/wallets'
      preLoaderRoute: typeof AuthenticatedWalletsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transactions': {
      id: '/_authenticated/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthenticatedTransactionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/transaction-detail': {
      id: '/_authenticated/transaction-detail'
      path: '/transaction-detail'
      fullPath: '/transaction-detail'
      preLoaderRoute: typeof AuthenticatedTransactionDetailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-supabase': {
      id: '/_authenticated/test-supabase'
      path: '/test-supabase'
      fullPath: '/test-supabase'
      preLoaderRoute: typeof AuthenticatedTestSupabaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-login-button': {
      id: '/_authenticated/test-login-button'
      path: '/test-login-button'
      fullPath: '/test-login-button'
      preLoaderRoute: typeof AuthenticatedTestLoginButtonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/test-datepicker': {
      id: '/_authenticated/test-datepicker'
      path: '/test-datepicker'
      fullPath: '/test-datepicker'
      preLoaderRoute: typeof AuthenticatedTestDatepickerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistics': {
      id: '/_authenticated/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AuthenticatedStatisticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editcategory': {
      id: '/_authenticated/editcategory'
      path: '/editcategory'
      fullPath: '/editcategory'
      preLoaderRoute: typeof AuthenticatedEditcategoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/budget': {
      id: '/_authenticated/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof AuthenticatedBudgetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBudgetRoute: typeof AuthenticatedBudgetRoute
  AuthenticatedEditcategoryRoute: typeof AuthenticatedEditcategoryRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatisticsRoute: typeof AuthenticatedStatisticsRoute
  AuthenticatedTestDatepickerRoute: typeof AuthenticatedTestDatepickerRoute
  AuthenticatedTestLoginButtonRoute: typeof AuthenticatedTestLoginButtonRoute
  AuthenticatedTestSupabaseRoute: typeof AuthenticatedTestSupabaseRoute
  AuthenticatedTransactionDetailRoute: typeof AuthenticatedTransactionDetailRoute
  AuthenticatedTransactionsRoute: typeof AuthenticatedTransactionsRoute
  AuthenticatedWalletsRoute: typeof AuthenticatedWalletsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBudgetRoute: AuthenticatedBudgetRoute,
  AuthenticatedEditcategoryRoute: AuthenticatedEditcategoryRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatisticsRoute: AuthenticatedStatisticsRoute,
  AuthenticatedTestDatepickerRoute: AuthenticatedTestDatepickerRoute,
  AuthenticatedTestLoginButtonRoute: AuthenticatedTestLoginButtonRoute,
  AuthenticatedTestSupabaseRoute: AuthenticatedTestSupabaseRoute,
  AuthenticatedTransactionDetailRoute: AuthenticatedTransactionDetailRoute,
  AuthenticatedTransactionsRoute: AuthenticatedTransactionsRoute,
  AuthenticatedWalletsRoute: AuthenticatedWalletsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotpasswordRoute: ForgotpasswordRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  OfflineRoute: OfflineRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  R5smsSplatRoute: R5smsSplatRoute,
  Sin1SplatRoute: Sin1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
