// Component: SignupContent
// Description: Renders the UI for the sign-up form (inputs, buttons, links, terms).
// To be used within the SignUp page component which handles state and logic.
// Initially generated by AI based on user prompt and refactored.

import React from 'react';
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox"; // Needed for terms agreement
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useId } from "react";
// Removed react-icons dependency for better performance
import { Link } from 'react-router-dom'; // For Terms and Privacy links

// Define props expected from the parent SignUp page
interface SignupContentProps {
  username: string;
  setUsername: (value: string) => void;
  email: string;
  setEmail: (value: string) => void;
  password: string;
  setPassword: (value: string) => void;
  agreedToTerms: boolean;
  setAgreedToTerms: (checked: boolean) => void;
  isSubmitting: boolean;
  handleEmailSignUp: (e: React.FormEvent) => Promise<void>;
  handleGoogleSignUp: () => Promise<void>;
}

function SignupContent({
  username,
  setUsername,
  email,
  setEmail,
  password,
  setPassword,
  agreedToTerms,
  setAgreedToTerms,
  isSubmitting,
  handleEmailSignUp,
  handleGoogleSignUp,
}: SignupContentProps) {
  const id = useId();

  return (
    <>
      {/* Google Sign Up Button - Kept separate as in original design */}
      <Button
          variant="outline"
          className="w-full py-6 border border-border bg-background text-foreground flex items-center justify-center gap-3 rounded-full hover:bg-accent" // Use theme colors
          onClick={handleGoogleSignUp}
          disabled={isSubmitting}
        >
          <div className="w-6 h-6 bg-white rounded-full flex items-center justify-center"> {/* Keep Google's branding style */}
            <svg className="h-4 w-4" viewBox="0 0 24 24">
              <path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"/>
              <path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"/>
              <path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"/>
              <path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"/>
            </svg>
          </div>
          <span className="font-medium">Sign up with Google</span>
      </Button>

      {/* Divider */}
      <div className="relative my-8"> {/* Added margin */}
        <div className="absolute inset-0 flex items-center">
          <div className="w-full border-t border-border"></div> {/* Use theme border */}
        </div>
        <div className="relative flex justify-center">
          {/* Use theme colors */}
          <span className="px-4 bg-background text-muted-foreground">or</span>
        </div>
      </div>

      {/* Email Sign Up Form */}
      <form onSubmit={handleEmailSignUp} className="space-y-6">
        <div className="space-y-4">
          <div className="space-y-2">
            {/* Use theme text color */}
            <Label htmlFor={`${id}-name`} className="text-foreground">Full name</Label>
            <Input
              id={`${id}-name`}
              placeholder="Faiz Intifada"
              type="text"
              required
              value={username} // Bind to username state
              onChange={(e) => setUsername(e.target.value)}
              // Removed specific dark theme classes
              className="h-auto py-3" // Adjust padding/height if needed
            />
          </div>
          <div className="space-y-2">
            {/* Use theme text color */}
            <Label htmlFor={`${id}-email`} className="text-foreground">Email</Label>
            <Input
              id={`${id}-email`}
              placeholder="hi@youremail.com"
              type="email"
              required
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              // Removed specific dark theme classes
               className="h-auto py-3" // Adjust padding/height if needed
            />
          </div>
          <div className="space-y-2">
             {/* Use theme text color */}
            <Label htmlFor={`${id}-password`} className="text-foreground">Password</Label>
            <Input
              id={`${id}-password`}
              placeholder="Enter your password"
              type="password"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              // Removed specific dark theme classes
              className="h-auto py-3" // Adjust padding/height if needed
            />
          </div>
        </div>

         {/* Terms Agreement - using Checkbox and Label */}
         <div className="flex items-start space-x-3 pt-2"> {/* Increased spacing */} 
              <Checkbox
                id={`${id}-terms`}
                checked={agreedToTerms}
                onCheckedChange={(checked) => {
                  setAgreedToTerms(checked as boolean);
                }}
                // Use theme colors for checkbox
              />
              <div className="grid gap-1.5 leading-none"> {/* Wrap label for better layout */} 
                <label
                  htmlFor={`${id}-terms`}
                  className="text-sm font-medium leading-none text-foreground peer-disabled:cursor-not-allowed peer-disabled:opacity-70" // Standard shadcn label style
                >
                 Accept terms and conditions
                </label>
                <p className="text-xs text-muted-foreground">
                    You agree to our{" "}
                    <Link to="/terms" className="text-primary underline hover:no-underline"> {/* Use theme primary */}
                       Terms of Service
                    </Link>{" "}and{" "}
                    <Link to="/privacy" className="text-primary underline hover:no-underline"> {/* Use theme primary */}
                       Privacy Policy
                    </Link>
                    .
                 </p>
               </div>
            </div>

        <Button
          type="submit"
          className="w-full" // Removed custom dark style, rely on ui/button
          disabled={isSubmitting}
        >
          {isSubmitting ? 'Signing Up...' : 'Sign up'}
        </Button>

        {/* Link to Login */}
         <p className="text-center text-sm text-muted-foreground">
           Already have an account?{' '}
            <Link to="/login" className="text-primary underline hover:no-underline">
              Log in
            </Link>
         </p>
      </form>
    </>
  );
}

export { SignupContent };